<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0"
          name="viewport">
    <meta content="ie=edge" http-equiv="X-UA-Compatible">
    <title>Lasd</title>
    <link href="css/freemarker.css" rel="stylesheet">
</head>

<body>
<main>

    <div class="container">
        <h1> ${book.name} ${book.author} </h1>
    </div>

</main>
</body>

</html>